/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppEmpty: typeof import('./components/AppEmpty/index.vue')['default']
    IMdiAccountCircleOutline: typeof import('~icons/mdi/account-circle-outline')['default']
    IMdiAccountOutline: typeof import('~icons/mdi/account-outline')['default']
    IMdiBroom: typeof import('~icons/mdi/broom')['default']
    IMdiCellphone: typeof import('~icons/mdi/cellphone')['default']
    IMdiClockOutline: typeof import('~icons/mdi/clock-outline')['default']
    IMdiCogOutline: typeof import('~icons/mdi/cog-outline')['default']
    IMdiFileQuestionOutline: typeof import('~icons/mdi/file-question-outline')['default']
    IMdiFormatListBulleted: typeof import('~icons/mdi/format-list-bulleted')['default']
    IMdiHandWaveOutline: typeof import('~icons/mdi/hand-wave-outline')['default']
    IMdiHomeOutline: typeof import('~icons/mdi/home-outline')['default']
    IMdiLogout: typeof import('~icons/mdi/logout')['default']
    IMdiShieldAccountOutline: typeof import('~icons/mdi/shield-account-outline')['default']
    IMdiShieldAlertOutline: typeof import('~icons/mdi/shield-alert-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
